name: ai_chat_kit_example
description: "Demonstrates how to use the ai_chat_kit package."
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ai_chat_kit:
    path: ../
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
